# This compose file is just for local / dev since we will deploy to k8s for staging and prod
version: '3'
services:
  consul:
    image: consul:1.5.3
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    restart: always  
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  micro_api:
    image: ilovelili/micro:1.8.2
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 api
    environment:      
      - MICRO_API_ADDRESS=0.0.0.0:8080
      - MICRO_API_NAMESPACE=dongfeng.svc.core.proxy
      - MICRO_API_HANDLER=http
      - CORS_ALLOWED_HEADERS=*
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,OPTIONS
    depends_on:
    - consul
    ports:
    - "8080:8080"