# This compose file is just for local / dev since we will deploy to k8s for staging and prod
version: '3'
services:
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    restart: always  
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  micro_api:
    image: ilovelili/micro:latest
    command: api
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul:8500
      - MICRO_API_ADDRESS=0.0.0.0:8080
      - MICRO_API_NAMESPACE=dongfeng.svc.core.proxy
      - MICRO_API_HANDLER=proxy
      - MICRO_API_CORS=*
    restart: always
    depends_on:
    - consul
    ports:
    - "8080:8080"
  chrome_headless:
    image: ilovelili/chrome_headless:latest    
    restart: always    
    ports:
    - "9222:9222"
  dongfeng.svc.core.server:
    image: ilovelili/dongfeng-core:latest    
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul:8500
      - CHROME_DEV_TOOL=chrome_headless:9222
    volumes:
      -  /root/dongfeng/ebook:/root/ebook
    restart: always
    depends_on:
    - consul
    - chrome_headless
  dongfeng.svc.core.proxy:
    image: ilovelili/dongfeng-core-proxy:latest    
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul:8500
    restart: always
    depends_on:
    - dongfeng.svc.core.server
    - micro_api
  dongfeng.admin.panel:
    image: ilovelili/dongfeng-admin-panel:prod
    restart: always
    ports:
    - "80:80"
    depends_on:
    - dongfeng.svc.core.proxy
    - dongfeng.svc.core.server
    - micro_api
#   mysql:
#     image: mysql:5.7
#     restart: always
#     volumes:
#       - dongfeng-core:/var/lib/mysql/
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: dongfeng_zhonglou
#       MYSQL_USER: dongfeng
#       MYSQL_PASSWORD: Aa!7059970599
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

# volumes: 
#   dongfeng-core:
