# This compose file is just for local / dev since we will deploy to k8s for staging and prod
version: '3'
services:
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    restart: always  
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"    
  micro_api:
    image: ilovelili/micro:latest
    command: api
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul:8500
      - MICRO_API_ADDRESS=0.0.0.0:8080
      - MICRO_API_NAMESPACE=dongfeng.svc.core.proxy
      - MICRO_API_HANDLER=proxy
      - MICRO_API_CORS="*"
    restart: always
    depends_on:
    - consul
    ports:
    - "8080:8080"
  dongfeng.svc.core.server:    
    image: ilovelili/dongfeng-core:latest
    command: [
      "./server"
    ]
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul:8500
    restart: always
    depends_on:
    - consul
  dongfeng.svc.attendance.server:    
    image: ilovelili/dongfeng-attendance:latest
    command: [
      "./server"
    ]
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul:8500
    restart: always
    depends_on:
    - consul
  # dongfeng.svc.physique.server:    
  #   image: ilovelili/dongfeng-physique:latest
  #   command: [
  #     "./server"
  #   ]
  #   environment:
  #     - MICRO_REGISTRY=consul
  #     - MICRO_REGISTRY_ADDRESS=consul:8500
  #   restart: always
  #   depends_on:
  #   - consul
  dongfeng.svc.core.proxy:    
    image: ilovelili/dongfeng-core-proxy:latest
    command: [
      "./server"
    ]
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul:8500      
    restart: always
    depends_on:    
    - dongfeng.svc.core.server
    - dongfeng.svc.attendance.server
    # - dongfeng.svc.physique.server
    - micro_api
  dongfeng.admin.panel:    
    image: ilovelili/dongfeng-admin-panel:prod
    restart: always
    ports:
    - "80:80"
    depends_on:
    - dongfeng.svc.core.proxy
    - dongfeng.svc.core.server
    - dongfeng.svc.attendance.server    
    - micro_api
  # dongfeng.svc.websocket:    
  #   image: ilovelili/dongfeng-websocket:latest
  #   command: [
  #     "./server"
  #   ]  
  #   restart: always 